Started logging messages at Mon Sep 22 00:21:51 2014
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: Off
Info:        Surfaces: On
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.0
Info:    Reading C:\Users\Sergey\Desktop\USERLI~1.SAT
Info:    Processing C:\Users\Sergey\Desktop\USERLI~1.SAT
Info:    Transferring C:\Users\Sergey\Desktop\USERLI~1.SAT
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 143 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 84
Info:            Created 
Info:        Working on 85
Info:            Created 
Info:        Working on 133
Info:            Created 
Info:        Working on 137
Info:            Created 
Info:        Working on 9
Info:            Created 
Info:        Working on 124
Info:            Created 
Info:        Working on 125
Info:            Created 
Info:        Working on 198
Info:            Created 
Info:        Working on 203
Info:            Created 
Info:        Working on 14
Info:            Created 
Info:        Working on 190
Info:            Created 
Info:        Working on 191
Info:            Created 
Info:        Working on 302
Info:            Created 
Info:        Working on 307
Info:            Created 
Info:        Working on 20
Info:            Created 
Info:        Working on 294
Info:            Created 
Info:        Working on 295
Info:            Created 
Info:        Working on 458
Info:            Created 
Info:        Working on 462
Info:            Created 
Info:        Working on 30
Info:            Created 
Info:        Working on 450
Info:            Created 
Info:        Working on 451
Info:            Created 
Info:        Working on 671
Info:            Created 
Info:        Working on 675
Info:            Created 
Info:        Working on 662
Info:            Created 
Info:        Working on 663
Info:            Created 
Info:        Working on 947
Info:            Created 
Info:        Working on 1321
Info:            Created 
Info:        Working on 1763
Info:            Created 
Info:        Working on 2194
Info:            Created 
Info:        Working on 2528
Info:            Created 
Info:        Working on 2381
Info:            Created 
Info:        Working on 2865
Info:            Created 
Info:        Working on 2987
Info:            Created 
Info:        Working on 2861
Info:            Created 
Info:        Working on 2971
Info:            Created 
Info:        Working on 3015
Info:            Created 
Info:        Working on 3018
Info:            Created 
Info:        Working on 3000
Info:            Created 
Info:        Working on 2968
Info:            Created 
Info:        Working on 2636
Info:            Created 
Info:        Working on 2637
Info:            Created 
Info:        Working on 2962
Info:            Created 
Info:        Working on 2963
Info:            Created 
Info:        Working on 2869
Info:            Created 
Info:        Working on 2674
Info:            Created 
Info:        Working on 2789
Info:            Created 
Info:        Working on 2545
Info:            Created 
Info:        Working on 2023
Info:            Created 
Info:        Working on 1794
Info:            Created 
Info:        Working on 1344
Info:            Created 
Info:        Working on 960
Info:            Created 
Info:        Working on 932
Info:            Created 
Info:        Working on 933
Info:            Created 
Info:        Working on 1293
Info:            Created 
Info:        Working on 1297
Info:            Created 
Info:        Working on 1285
Info:            Created 
Info:        Working on 1286
Info:            Created 
Info:        Working on 1711
Info:            Created 
Info:        Working on 1715
Info:            Created 
Info:        Working on 51
Info:            Created 
Info:        Working on 625
Info:            Created 
Info:        Working on 626
Info:            Created 
Info:        Working on 888
Info:            Created 
Info:        Working on 893
Info:            Created 
Info:        Working on 90
Info:            Created 
Info:        Working on 878
Info:            Created 
Info:        Working on 879
Info:            Created 
Info:        Working on 1212
Info:            Created 
Info:        Working on 1630
Info:            Created 
Info:        Working on 2078
Info:            Created 
Info:        Working on 2447
Info:            Created 
Info:        Working on 2718
Info:            Created 
Info:        Working on 2896
Info:            Created 
Info:        Working on 2916
Info:            Created 
Info:        Working on 2747
Info:            Created 
Info:        Working on 2474
Info:            Created 
Info:        Working on 2104
Info:            Created 
Info:        Working on 1649
Info:            Created 
Info:        Working on 1223
Info:            Created 
Info:        Working on 1198
Info:            Created 
Info:        Working on 1199
Info:            Created 
Info:        Working on 1606
Info:            Created 
Info:        Working on 1610
Info:            Created 
Info:        Working on 155
Info:            Created 
Info:        Working on 1180
Info:            Created 
Info:        Working on 1181
Info:            Created 
Info:        Working on 1585
Info:            Created 
Info:        Working on 2029
Info:            Created 
Info:        Working on 2411
Info:            Created 
Info:        Working on 2575
Info:            Created 
Info:        Working on 2280
Info:            Created 
Info:        Working on 2809
Info:            Created 
Info:        Working on 2982
Info:            Created 
Info:        Working on 2892
Info:            Created 
Info:        Working on 2706
Info:            Created 
Info:        Working on 2422
Info:            Created 
Info:        Working on 2043
Info:            Created 
Info:        Working on 1594
Info:            Created 
Info:        Working on 254
Info:            Created 
Info:        Working on 1365
Info:            Created 
Info:        Working on 1359
Info:            Created 
Info:        Working on 1813
Info:            Created 
Info:        Working on 1817
Info:            Created 
Info:        Working on 398
Info:            Created 
Info:        Working on 2022
Info:            Created 
Info:        Working on 2394
Info:            Created 
Info:        Working on 2881
Info:            Created 
Info:        Working on 2546
Info:            Created 
Info:        Working on 588
Info:            Created 
Info:        Working on 2382
Info:            Created 
Info:        Working on 2558
Info:            Created 
Info:        Working on 2796
Info:            Created 
Info:        Working on 2660
Info:            Created 
Info:        Working on 833
Info:            Created 
Info:        Working on 2223
Info:            Created 
Info:        Working on 2709
Info:            Created 
Info:        Working on 2045
Info:            Created 
Info:        Working on 1801
Info:            Created 
Info:        Working on 1157
Info:            Created 
Info:        Working on 2844
Info:            Created 
Info:        Working on 2856
Info:            Created 
Info:        Working on 2952
Info:            Created 
Info:        Working on 2852
Info:            Created 
Info:        Working on 2994
Info:            Created 
Info:        Working on 3007
Info:            Created 
Info:        Working on 1560
Info:            Created 
Info:        Working on 2599
Info:            Created 
Info:        Working on 2820
Info:            Created 
Info:        Working on 2921
Info:            Created 
Info:        Working on 2843
Info:            Created 
Info:        Working on 3019
Info:            Created 
Info:        Working on 3017
Info:            Created 
Info:        Working on 1996
Info:            Created 
Info:        Working on 2903
Info:            Created 
Info:        Working on 2307
Info:            Created 
Info:        Working on 2984
Info:            Created 
Info:        Working on 2366
Info:            Created 
Info:        Working on 2649
Info:            Created 
Info:        Working on 495
Info:            Created 
Info:        Working on 742
Info:            Created 
Info:        Working on 1047
Info:            Created 
Info:        Working on 1421
Info:            Created 
Info:        Working on 1405
Info:            Created 
Info:        Working on 1031
Info:            Created 
Info:        Working on 717
Info:            Created 
Info:        Working on 709
Info:            Created 
Info:        Working on 1021
Info:            Created 
Info:        Working on 1058
Info:            Created 
Info:        Working on 750
Info:            Created 
Info:        Working on 502
Info:            Created 
Info:        Working on 320
Info:            Created 
Info:        Working on 1878
Info:            Created 
Info:        Working on 1879
Info:            Created 
Info:        Working on 2208
Info:            Created 
Info:        Working on 2935
Info:            Created 
Info:        Working on 2996
Info:            Created 
Info:        Working on 2951
Info:            Created 
Info:        Working on 2590
Info:            Created 
Info:        Working on 2591
Info:            Created 
Info:        Working on 2351
Info:            Created 
Info:        Working on 2262
Info:            Created 
Info:        Working on 506
Info:            Created 
Info:        Working on 523
Info:            Created 
Info:        Working on 514
Info:            Created 
Info:        Working on 1067
Info:            Created 
Info:        Working on 1105
Info:            Created 
Info:        Working on 793
Info:            Created 
Info:        Working on 369
Info:            Created 
Info:        Working on 363
Info:            Created 
Info:        Working on 790
Info:            Created 
Info:        Working on 1104
Info:            Created 
Info:        Working on 1492
Info:            Created 
Info:        Working on 1454
Info:            Created 
Info:        Working on 1075
Info:            Created 
Info:        Working on 361
Info:            Created 
Info:        Working on 1951
Info:            Created 
Info:        Working on 1952
Info:            Created 
Info:        Working on 2315
Info:            Created 
Info:        Working on 2319
Info:            Created 
Info:        Working on 2306
Info:            Created 
Info:        Working on 2465
Info:            Created 
Info:        Working on 1662
Info:            Created 
Info:        Working on 2112
Info:            Created 
Info:        Working on 1979
Info:            Created 
Info:        Working on 1544
Info:            Created 
Info:        Working on 2360
Info:            Created 
Info:        Working on 556
Info:            Created 
Info:        Working on 1545
Info:            Created 
Info:        Working on 1860
Info:            Created 
Info:        Working on 1981
Info:            Created 
Info:        Working on 2268
Info:            Created 
Info:        Working on 1885
Info:            Created 
Info:        Working on 2267
Info:            Created 
Info:        Working on 2577
Info:            Created 
Info:        Working on 2352
Info:            Created 
Info:        Working on 2639
Info:            Created 
Info:        Working on 2568
Info:            Created 
Info:        Working on 1857
Info:            Created 
Info:        Working on 1430
Info:            Created 
Info:        Working on 798
Info:            Created 
Info:        Working on 2585
Info:            Created 
Info:        Working on 1917
Info:            Created 
Info:        Working on 1916
Info:            Created 
Info:        Working on 1110
Info:            Created 
Info:        Working on 2281
Info:            Created 
Info:        Working on 2256
Info:            Created 
Info:        Working on 1496
Info:            Created 
Info:        Working on 1520
Info:            Created 
Info:        Working on 1479
Info:            Created 
Info:        Working on 1904
Info:            Created 
Info:        Working on 1921
Info:            Created 
Info:        Working on 2274
Info:            Created 
Info:        Working on 2807
Info:            Created 
Info:        Working on 2290
Info:            Created 
Info:        Working on 1660
Info:            Created 
Info:        Working on 2109
Info:            Created 
Info:        Working on 1888
Info:            Created 
Info:        Working on 2479
Info:            Created 
Info:        Working on 1097
Info:            Created 
Info:        Working on 769
Info:            Created 
Info:        Working on 1082
Info:            Created 
Info:        Working on 2477
Info:            Created 
Info:        Working on 2645
Info:            Created 
Info:        Working on 2251
Info:            Created 
Info:        Working on 1465
Info:            Created 
Info:        Working on 1038
Info:            Created 
Info:        Working on 1845
Info:            Created 
Info:        Working on 1055
Info:            Created 
Info:        Working on 1435
Info:            Created 
Info:        Working on 1554
Info:            Created 
Info:        Working on 1990
Info:            Created 
Info:        Working on 1863
Info:            Created 
Info:        Working on 811
Info:            Created 
Info:        Working on 779
Info:            Created 
Info:        Working on 1470
Info:            Created 
Info:        Working on 1894
Info:            Created 
Info:        Working on 1655
Info:            Created 
Info:        Working on 536
Info:            Created 
Info:        Working on 345
Info:            Created 
Info:        Working on 784
Info:            Created 
Info:        Working on 1101
Info:            Created 
Info:        Working on 728
Info:            Created 
Info:        Working on 1152
Info:            Created 
Info:        Working on 1415
Info:            Created 
Info:        Working on 1096
Info:            Created 
Info:        Working on 352
Info:            Created 
Info:        Working on 573
Info:            Created 
Info:        Working on 387
Info:            Created 
Info:        Working on 244
Info:            Created 
Info:        Working on 236
Info:            Created 
Info:        Working on 378
Info:            Created 
Info:        Working on 563
Info:            Created 
Info:        Working on 542
Info:            Created 
Info:        Working on 150
Info:            Created 
Info:        Working on 722
Info:            Created 
Info:        Working on 1411
Info:            Created 
Info:        Working on 1844
Info:            Created 
Info:        Working on 1836
Info:            Created 
Info:        Working on 1011
Info:            Created 
Info:        Working on 1008
Info:            Created 
Info:        Working on 1834
Info:            Created 
Info:        Working on 2247
Info:            Created 
Info:        Working on 249
Info:            Created 
Info:        Working on 392
Info:            Created 
Info:        Working on 579
Info:            Created 
Info:        Working on 817
Info:            Created 
Info:        Working on 1130
Info:            Created 
Info:        Working on 1525
Info:            Created 
Info:        Working on 2573
Info:            Created 
Info:        Working on 2198
Info:            Created 
Info:        Working on 2413
Info:            Created 
Info:        Working on 1965
Info:            Created 
Info:        Working on 2206
Info:            Created 
Info:        Working on 1779
Info:            Created 
Info:        Working on 2345
Info:            Created 
Info:        Working on 2888
Info:            Created 
Info:        Working on 2883
Info:            Created 
Info:        Working on 2689
Info:            Created 
Info:        Working on 2407
Info:            Created 
Info:        Working on 3014
Info:            Created 
Info:        Working on 2997
Info:            Created 
Info:        Working on 2699
Info:            Created 
Info:        Working on 2877
Info:            Created 
Info:        Working on 2875
Info:            Created 
Info:        Working on 2949
Info:            Created 
Info:        Working on 2046
Info:            Created 
Info:        Working on 1333
Info:            Created 
Info:        Working on 2907
Info:            Created 
Info:        Working on 2822
Info:            Created 
Info:        Working on 2454
Info:            Created 
Info:        Working on 1786
Info:            Created 
Info:        Working on 2910
Info:            Created 
Info:        Working on 2738
Info:            Created 
Info:        Working on 2212
Info:            Created 
Info:        Working on 2093
Info:            Created 
Info:        Working on 1639
Info:            Created 
Info:        Working on 1234
Info:            Created 
Info:        Working on 1667
Info:            Created 
Info:        Working on 2115
Info:            Created 
Info:        Working on 2249
Info:            Created 
Info:        Working on 1842
Info:            Created 
Info:        Working on 1408
Info:            Created 
Info:        Working on 695
Info:            Created 
Info:        Working on 702
Info:            Created 
Info:        Working on 1015
Info:            Created 
Info:        Working on 1397
Info:            Created 
Info:        Working on 1438
Info:            Created 
Info:        Working on 1061
Info:            Created 
Info:        Working on 479
Info:            Created 
Info:        Working on 487
Info:            Created 
Info:        Working on 337
Info:            Created 
Info:        Working on 329
Info:            Created 
Info:        Working on 518
Info:            Created 
Info:        Working on 765
Info:            Created 
Info:        Working on 807
Info:            Created 
Info:        Working on 566
Info:            Created 
Info:        Working on 229
Info:            Created 
Info:        Working on 223
Info:            Created 
Info:        Working on 367
Info:            Created 
Info:        Working on 560
Info:            Created 
Info:        Working on 804
Info:            Created 
Info:        Working on 1121
Info:            Created 
Info:        Working on 2804
Info:            Created 
Info:        Working on 2940
Info:            Created 
Info:        Working on 1517
Info:            Created 
Info:        Working on 1957
Info:            Created 
Info:        Working on 2331
Info:            Created 
Info:        Working on 2221
Info:            Created 
Info:        Working on 1799
Info:            Created 
Info:        Working on 1352
Info:            Created 
Info:        Working on 1807
Info:            Created 
Info:        Working on 2229
Info:            Created 
Info:        Working on 2552
Info:            Created 
Info:        Working on 2792
Info:            Created 
Info:        Working on 2741
Info:            Created 
Info:        Working on 2914
Info:            Created 
Info:        Working on 2681
Info:            Created 
Info:        Working on 2880
Info:            Created 
Info:        Working on 2240
Info:            Created 
Info:        Working on 1770
Info:            Created 
Info:        Working on 2202
Info:            Created 
Info:        Working on 2534
Info:            Created 
Info:        Working on 2782
Info:            Created 
Info:        Working on 2931
Info:            Created 
Info:        Working on 2034
Info:            Created 
Info:        Working on 2085
Info:            Created 
Info:        Working on 2459
Info:            Created 
Info:        Working on 2733
Info:            Created 
Info:        Working on 2617
Info:            Created 
Info:        Working on 2618
Info:            Created 
Info:        Working on 2327
Info:            Created 
Info:        Working on 2828
Info:            Created 
Info:        Working on 2609
Info:            Created 
Info:        Working on 2831
Info:            Created 
Info:        Working on 2826
Info:            Created 
Info:        Working on 2615
Info:            Created 
Info:        Working on 1692
Info:            Created 
Info:        Working on 1683
Info:            Created 
Info:        Working on 2131
Info:            Created 
Info:        Working on 2135
Info:            Created 
Info:        Working on 2490
Info:            Created 
Info:        Working on 2064
Info:            Created 
Info:        Working on 2065
Info:            Created 
Info:        Working on 1618
Info:            Created 
Info:        Working on 2437
Info:            Created 
Info:        Working on 2061
Info:            Created 
Info:        Working on 2432
Info:            Created 
Info:        Working on 2430
Info:            Created 
Info:        Working on 2055
Info:            Created 
Info:        Working on 2435
Info:            Created 
Info:        Working on 1671
Info:            Created 
Info:        Working on 1261
Info:            Created 
Info:        Working on 2491
Info:            Created 
Info:        Working on 2137
Info:            Created 
Info:        Working on 1258
Info:            Created 
Info:        Working on 2486
Info:            Created 
Info:        Working on 1700
Info:            Created 
Info:        Working on 1262
Info:            Created 
Info:        Working on 2124
Info:            Created 
Info:        Working on 1247
Info:            Created 
Info:        Working on 1687
Info:            Created 
Info:        Working on 902
Info:            Created 
Info:        Working on 1266
Info:            Created 
Info:        Working on 1750
Info:            Created 
Info:        Working on 2179
Info:            Created 
Info:        Working on 1703
Info:            Created 
Info:        Working on 2188
Info:            Created 
Info:        Working on 2185
Info:            Created 
Info:        Working on 1745
Info:            Created 
Info:        Working on 1309
Info:            Created 
Info:        Working on 2181
Info:            Created 
Info:        Working on 1740
Info:            Created 
Info:        Working on 2771
Info:            Created 
Info:        Working on 2772
Info:            Created 
Info:        Working on 2177
Info:            Created 
Info:        Working on 2520
Info:            Created 
Info:        Working on 995
Info:            Created 
Info:        Working on 1375
Info:            Created 
Info:        Working on 979
Info:            Created 
Info:        Working on 1385
Info:            Created 
Info:        Working on 1382
Info:            Created 
Info:        Working on 990
Info:            Created 
Info:        Working on 687
Info:            Created 
Info:        Working on 1378
Info:            Created 
Info:        Working on 985
Info:            Created 
Info:        Working on 2242
Info:            Created 
Info:        Working on 2243
Info:            Created 
Info:        Working on 1373
Info:            Created 
Info:        Working on 1825
Info:            Created 
Info:        Working on 2164
Info:            Created 
Info:        Working on 2501
Info:            Created 
Info:        Working on 2148
Info:            Created 
Info:        Working on 2511
Info:            Created 
Info:        Working on 2508
Info:            Created 
Info:        Working on 2159
Info:            Created 
Info:        Working on 1727
Info:            Created 
Info:        Working on 2504
Info:            Created 
Info:        Working on 2154
Info:            Created 
Info:        Working on 2923
Info:            Created 
Info:        Working on 2924
Info:            Created 
Info:        Working on 2499
Info:            Created 
Info:        Working on 2763
Info:            Created 
Info:        Working on 2526
Info:            Created 
Info:        Working on 2523
Info:            Created 
Info:        Working on 2769
Info:            Created 
Info:        Working on 2766
Info:            Created 
Info:        Working on 1831
Info:            Created 
Info:        Working on 1828
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Created BRep 
Info:    Finished with C:\Users\Sergey\Desktop\USERLI~1.SAT
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
